version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:13.12.0
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          # only run if build succeeds
          requires:
            - build
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: echo "Build Done"
  test:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
