version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:13.12.0
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test-1:
          # only run if build succeeds
          requires:
            - build
      - test-2:
          # only run if build succeeds
          requires:
            - build
      - deploy:
          # only run if test succeeds
          requires:
            - test-1
            - test-2
jobs:
  build:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: echo "Build Done"
  test-1:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm run test
  test-2:
    executor: node
    steps:
      - checkout
      - run: echo "Test 2 Done"
  deploy:
    executor: node
    steps:
      - checkout
      - run: echo "Deploy Done"
